[package]
name = "cluj-lending"
version = "0.1.0"
edition = "2024"

[dependencies]
stylus-sdk = "0.10.5"
alloy-sol-types = ">=0.0.0"

[features]
contract-client-gen = []
export-abi = ["stylus-sdk/export-abi"]

[lib]
crate-type = ["lib", "cdylib"]

[[bin]]
name = "cluj-lending"
path = "src/main.rs"

[profile.release]
codegen-units = 1
opt-level = "z"
strip = true
lto = "fat"
debug = false
panic = "abort"

[dev-dependencies]
stylus-sdk = { version = "0.10.5", features = ["stylus-test"] }
proptest = "1.11.0"
proptest-derive = "0.8.0"
