[package]
name = "cluj-calling-out"
version = "0.1.0"
edition = "2024"

[profile.release]
codegen-units = 1
opt-level = "z"
strip = false
lto = "fat"
debug = false
rpath = false
debug-assertions = false
incremental = false

[dependencies]
const-hex = { version = "1.19.0", default-features = false }
